### ISSUE TITLE
Add development instructions

### ISSUE THREAD

**Issue by manning-ncsa** [USRSE/usrse23#5]
I cloned the repo and could not find instructions for how to build or develop the site locally, so I naively tried a `docker build` that failed on [line 4 of the Dockerfile](https://github.com/USRSE/usrse23/blob/main/Dockerfile#L4) because there is no `Gemfile.lock` file. Also there is obviously a missing line that copies in the source files. Can someone explain how to build and run the site locally? I'd be happy to contribute this documentation once I demonstrate the workflow to do so.

**Comment by mrmundt** [comment]
I have instructions for this actually - let me add them to the README.
